name: PR GitHub Actions Bot
run-name: ${{ github.actor }} is working on a feature 🚀
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run lint
      - run: npm run test -- --coverage --maxWorkers=4 --ci
      - name: Check code coverage
        run: |
          npx check-coverage --statements 80 --branches 80 --functions 80 --lines 80 ./coverage/lcov.info
        env:
          CI: true
