name: PR GitHub Actions Bot
run-name: ${{ github.actor }} is working on a feature 🚀
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install packages using yarn
        run: yarn install
      - name: Run unit tests
        run: yarn test --coverage --watchAll=false
      - name: Check code coverage
        run: |
          yarn run test:coverage
        env:
          CI: true
